import Head from "next/head";
import { useRef } from "react";
import styles from "../styles/Home.module.css";

import Video from "../components/video";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create in-video ads in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Create in-video ads in Next.js</h1>
        <Video />
      </main>
    </div>
  );
}
